# Generated by Django 2.0.2 on 2019-10-15 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20, verbose_name='班级姓名')),
                ('gdate', models.DateTimeField(verbose_name='成立时间')),
                ('ggirlnum', models.IntegerField(verbose_name='女生总数')),
                ('gboynum', models.IntegerField(verbose_name='男生总数')),
                ('idDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('sgender', models.BooleanField(default=True, verbose_name='学生性别')),
                ('sage', models.IntegerField(verbose_name='学生年龄')),
                ('scontend', models.CharField(max_length=20, verbose_name='学生简介')),
                ('isDelete', models.BooleanField(default=False)),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades')),
            ],
        ),
    ]
