# Generated by Django 2.0.2 on 2019-10-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('project_version', models.CharField(max_length=10, verbose_name='项目版本')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('user_age', models.CharField(max_length=3, verbose_name='年龄')),
                ('user_position', models.CharField(max_length=10, verbose_name='职位')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='create_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.User'),
        ),
    ]
